### ISSUE TITLE
Output to Webp Not working

### ISSUE THREAD

**Issue by thefran1412** [gumlet/gif-resize#5]
Hi, i just tried to convert gif to webp and I can't get it to work. If i use the same exact configuration but with  `output_webp: false` it works fine, but when `true` it returns error.

Here's my code:
```js
const buffer = await gifResize({
   width: 200,
   height: 200,
   optimization: 3,
   output_webp: true
})(file.buffer)
```

Thanks in advance!

**Comment by thefran1412** [comment]
I need the `gif2webp` binaries to make it work

**Comment by adityapatadia** [comment]
gif2webp must be installed on the system for this to work.
