### ISSUE TITLE
output_webp Not Supported

### ISSUE THREAD

**Issue by winrid** [gumlet/gif-resize#8]
Hello,

Maybe not a major issue since [I can't find the corresponding setting in gifsicle](https://www.lcdf.org/gifsicle/man.html) but output_webp is listed in the documentation but doesn't do anything.

**Comment by adityapatadia** [comment]
You can use 1.1.1 version which supports it. We have removed it from library in latest version but you can obviously write your own code to take output buffer and convert it to WebP.

Here is sample code

```javscript
await execa("gif2webp", ['-quiet','-min_size', '-mt', '-metadata', 'none', '-q', '85', '-m', '2', '-lossy', '-o', '-', '--', '-'], {input: gif_output.stdout, encoding: null});
```
